replicaCount: 1

image:
  repository: adir3001/rick-and-morty-api    # ← שם מלא של ה-Docker Image שלך
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  host: rick.local
  path: /

resources: {}