
name: Deploy to AWS EKS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/rick-and-morty-api:${{ env.IMAGE_TAG }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name rick-cluster

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Deploy with Helm to EKS
        run: |
          helm upgrade --install rick-and-morty-api ./helm \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/rick-and-morty-api \
            --set image.tag=${{ env.IMAGE_TAG }}

      - name: Wait for deployment to be ready
        run: |
          echo "Waiting for service to become available..."
          kubectl wait --for=condition=available --timeout=90s deployment/rick-and-morty-api

      - name: Debug – Get resources and logs
        if: always()
        run: |
          echo "📦 Kubernetes Resources:"
          kubectl get all
          echo "🔍 Describe Deployment:"
          kubectl describe deployment rick-and-morty-api || true
          echo "📝 Pod Logs:"
          POD_NAME=$(kubectl get pods -l app=rick-and-morty-api -o jsonpath="{.items[0].metadata.name}")
          kubectl logs $POD_NAME || true